# Generated by Django 5.1 on 2026-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
